[default]
src = 'src'
out = 'out'
libs = ["node_modules", "lib"]

gas_reports = ["*"]
optimizer = true

remappings = [
    '@openzeppelin/=node_modules/@openzeppelin/',
    'hardhat-deploy/=node_modules/hardhat-deploy/',
    'hardhat/=node_modules/hardhat/',
]

optimizer_runs = 20000
solc_version = "0.8.13"
# See more config options https://github.com/foundry-rs/foundry/tree/master/config